# Auto-Generated by cargo-bitbake 0.3.10-pre
#
inherit cargo

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

# how to get xmz-test-gui could be as easy as but default to a git checkout:
# SRC_URI += "crate://crates.io/xmz-test-gui/0.1.1"
SRC_URI += "git://git@github.com/zzeroo/xmz-test-gui.git;protocol=ssh"
SRCREV = "7d2579eae082b3933af2d368480afad49ba98800"
S = "${WORKDIR}/git"
CARGO_SRC_DIR=""
PV_append = ".AUTOINC+7d2579eae0"

# please note if you have entries that do not begin with crate://
# you must change them to how that package can be fetched
SRC_URI += " \
crate://crates.io/atk-sys/0.5.0 \
crate://crates.io/bitflags/1.0.1 \
crate://crates.io/c_vec/1.2.1 \
crate://crates.io/cairo-rs/0.3.0 \
crate://crates.io/cairo-sys-rs/0.5.0 \
crate://crates.io/gdk-pixbuf-sys/0.5.0 \
crate://crates.io/gdk-pixbuf/0.3.0 \
crate://crates.io/gdk-sys/0.5.0 \
crate://crates.io/gdk/0.7.0 \
crate://crates.io/gio-sys/0.5.0 \
crate://crates.io/gio/0.3.0 \
crate://crates.io/glib-sys/0.5.0 \
crate://crates.io/glib/0.4.0 \
crate://crates.io/gobject-sys/0.5.0 \
crate://crates.io/gtk-sys/0.5.0 \
crate://crates.io/gtk/0.3.0 \
crate://crates.io/lazy_static/0.2.11 \
crate://crates.io/libc/0.2.34 \
crate://crates.io/pango-sys/0.5.0 \
crate://crates.io/pango/0.3.0 \
crate://crates.io/pkg-config/0.3.9 \
crate://crates.io/winapi/0.2.8 \
"



# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM=" \
"

SUMMARY = "Simple test GUI"
HOMEPAGE = "https://github.com/zzeroo/xmz-test-gui"
LICENSE = "CLOSED"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include xmz-test-gui-${PV}.inc
include xmz-test-gui.inc
